notification-engine/main/default/objects/Notification__c/Notification__c.object-meta.xml
<CustomObject>
    <description>This object stores the individual notification. The notification can be linked to a group. If linked to a group, the notifications are batched together, and the Title and body are taken from the group.</description>
    <label>Notification</label>
    <nameField>
        <displayFormat>NOTIF-{YYYY}{MM}{DD}-{00000}</displayFormat>
        <label>#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

notification-engine/main/default/objects/Notification__c/fields/NotificationType__c.field-meta.xml
<CustomField>
    <fullName>NotificationType__c</fullName>
    <inlineHelpText>The custom notification Developer name created in Salesforce.</inlineHelpText>
    <label>Notification Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NotificationType</valueSetName>
    </valueSet>
</CustomField>

notification-engine/main/default/objects/Notification__c/fields/TargetId__c.field-meta.xml
<CustomField>
    <fullName>TargetId__c</fullName>
    <defaultValue>&apos;000000000000000AAA&apos;</defaultValue>
    <inlineHelpText>This field is ignored if a notification is grouped. Target Id of the record where to send the user after clicking page. You can either provide this or
        the target page reference value.</inlineHelpText>
    <label>Target Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

notification-engine/main/default/objects/Notification__c/fields/TargetReference__c.field-meta.xml
<CustomField>
    <fullName>TargetReference__c</fullName>
    <inlineHelpText>This field is ignored if a notification is grouped.Target page reference where to send the user
        after clicking page. You can either provide this or the target Id value.</inlineHelpText>
    <label>Target Page reference</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

notification-engine/main/default/globalValueSets/NotificationType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>SFDefaultNotification</fullName>
        <label>SF Default Notification (notification-engine)</label>
    </customValue>
    <masterLabel>Notification Type</masterLabel>
</GlobalValueSet>

notification-engine/main/default/classes/SFNotificationBatchTest.cls
/**
 *
 * @description Test class for SFNotificationBatch
 *
 * @see SFNotificationBatch
 *
 * @date 2021-02-07
 * @author Manjit Singh
 */
@IsTest(SeeAllData=false)
private with sharing class SFNotificationBatchTest {
    @TestSetup private static void createData() {
        insert new Account(Name = 'SFNotificationSchedulerTest');
    }

    @IsTest private static void batchSuccessTest() {
        Account account = [SELECT Id FROM Account LIMIT 1];
        SFNotification notif = new SFNotification(SFNotificationConstants.DEFAULT_NOTIFICATION_TYPE);

        notif.setRecordId(account.Id).setBody('Body').setTitle('Title')
                .addRecipient(UserInfo.getUserId()).setPriority(1000).enqueue();

        Notification__c notification = [SELECT Status__c FROM Notification__c LIMIT 1];

        System.assertEquals(SFNotificationConstants.QUEUED, notification.Status__c,
                SFNotificationConstants.TEST_MESSAGE_ONE_NOTIF_QUEUED);

        Test.startTest();
        Database.executeBatch(new SFNotificationBatch(SFNotificationConstants.QUERY_BATCH), 200);
        Test.stopTest();
        notification = [
                SELECT Status__c, TargetReference__c, TargetId__c
                FROM Notification__c
                LIMIT 1
        ];

        System.assertEquals(SFNotificationConstants.SUCCESS, notification.Status__c,
                SFNotificationConstants.TEST_MESSAGE_BATCH_SUCCESS);

    }

    @IsTest private static void batchFailureTest() {
        Account account = [SELECT Id FROM Account LIMIT 1];
        SFNotification notif = new SFNotification(SFNotificationConstants.DEFAULT_NOTIFICATION_TYPE);

        notif.setRecordId(account.Id).setBody('Body').setTitle('Title')
                .addRecipient(UserInfo.getUserId()).setPriority(1000).enqueue();

        Notification__c notification = [
                SELECT Status__c, TargetReference__c, TargetId__c, NotificationType__c
                FROM Notification__c
                LIMIT 1
        ];


        System.assertEquals(SFNotificationConstants.QUEUED, notification.Status__c,
                SFNotificationConstants.TEST_MESSAGE_ONE_NOTIF_QUEUED);

        new SFNotificationBatch(SFNotificationConstants.QUERY_BATCH).execute(null, new List<Notification__c>{
                notification
        });

        notification = [
                SELECT Status__c, TargetReference__c, TargetId__c
                FROM Notification__c
                LIMIT 1
        ];

        System.assertEquals(SFNotificationConstants.ERROR, notification.Status__c,
                SFNotificationConstants.TEST_MESSAGE_BATCH_FAILURE);

    }
}