notification-engine/main/default/objects/Notification__c/Notification__c.object-meta.xml
<CustomObject>
    <description>This object stores the individual notification. The notification can be linked to a group. If linked to a group, the notifications are batched together, and the Title and body are taken from the group.</description>
    <label>Notification</label>
    <nameField>
        <displayFormat>NOTIF-{YYYY}{MM}{DD}-{00000}</displayFormat>
        <label>#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

notification-engine/main/default/objects/Notification__c/fields/Body__c.field-meta.xml
<CustomField>
    <fullName>Body__c</fullName>
    <description>Write the body of the notification. This field support merge fields for user object. Example: {!User.Field__c} messages with values larger than 750 characters will be truncated.</description>
    <inlineHelpText>Write the body of the notification. This field support merge fields for user object. Example: {!User.Field__c} messages with values larger than 750 characters will be truncated.</inlineHelpText>
    <label>Body</label>
    <length>750</length>
    <type>LongTextArea</type>
</CustomField>

notification-engine/main/default/objects/Notification__c/fields/Error__c.field-meta.xml
<CustomField>
    <fullName>Error__c</fullName>
    <description>Stores error message for notification if any</description>
    <inlineHelpText>Error message</inlineHelpText>
    <label>Error</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

notification-engine/main/default/objects/Notification__c/fields/Group__c.field-meta.xml
<CustomField>
    <fullName>Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The group with which this notification is attached to.</description>
    <label>Group</label>
    <referenceTo>NotificationGroup__c</referenceTo>
    <relationshipLabel>Notifications</relationshipLabel>
    <relationshipName>Notifications</relationshipName>
    <type>Lookup</type>
</CustomField>

notification-engine/main/default/objects/Notification__c/fields/NotificationType__c.field-meta.xml
<CustomField>
    <fullName>NotificationType__c</fullName>
    <inlineHelpText>The custom notification Developer name created in Salesforce.</inlineHelpText>
    <label>Notification Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NotificationType</valueSetName>
    </valueSet>
</CustomField>

notification-engine/main/default/objects/Notification__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <inlineHelpText>Set the priority for this notification. Lesser the number higher the priority. If two notifications/groups have same priority, the one created earlier is given priority.</inlineHelpText>
    <label>Priority</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

notification-engine/main/default/objects/Notification__c/fields/TargetId__c.field-meta.xml
<CustomField>
    <fullName>TargetId__c</fullName>
    <defaultValue>&apos;000000000000000AAA&apos;</defaultValue>
    <inlineHelpText>This field is ignored if a notification is grouped. Target Id of the record where to send the user after clicking page. You can either provide this or
        the target page reference value.</inlineHelpText>
    <label>Target Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

notification-engine/main/default/objects/Notification__c/fields/TargetReference__c.field-meta.xml
<CustomField>
    <fullName>TargetReference__c</fullName>
    <inlineHelpText>This field is ignored if a notification is grouped.Target page reference where to send the user
        after clicking page. You can either provide this or the target Id value.</inlineHelpText>
    <label>Target Page reference</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

notification-engine/main/default/objects/Notification__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <description>Write the title of the notification. This field support merge fields for user object. Example: {!User.Field__c} messages with values larger than 250 characters will be truncated.</description>
    <externalId>true</externalId>
    <inlineHelpText>Write the title of the notification. This field support merge fields for user object. Example: {!User.Field__c} messages with values larger than 250 characters will be truncated.</inlineHelpText>
    <label>Title</label>
    <length>250</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

notification-engine/main/default/objects/NotificationGroup__c/NotificationGroup__c.object-meta.xml
<CustomObject>
    <description>A notification group which stores a single message to be sent to users. This can be a login message/welcome message etc or some other generic message.</description>
    <label>Notification Group</label>
    <nameField>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notification Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

notification-engine/main/default/objects/NotificationGroup__c/fields/Body__c.field-meta.xml
<CustomField>
    <fullName>Body__c</fullName>
    <inlineHelpText>Write the body of the notification. This field support merge fields for user object. Example: {!User.Field__c} messages with values larger than 750 characters will be truncated.</inlineHelpText>
    <label>Body</label>
    <length>750</length>
    <type>LongTextArea</type>
</CustomField>

notification-engine/main/default/objects/NotificationGroup__c/fields/NotificationType__c.field-meta.xml
<CustomField>
    <fullName>NotificationType__c</fullName>
    <label>Notification Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NotificationType</valueSetName>
    </valueSet>
</CustomField>

notification-engine/main/default/objects/NotificationGroup__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of this notification message.</description>
    <inlineHelpText>Status of this notification. Success means that notification was sent successfully, the delivery depends on reciever.</inlineHelpText>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Queued</fullName>
                <default>true</default>
                <label>Queued</label>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

notification-engine/main/default/objects/NotificationGroup__c/fields/TargetId__c.field-meta.xml
<CustomField>
    <fullName>TargetId__c</fullName>
    <defaultValue>&apos;000000000000000AAA&apos;</defaultValue>
    <inlineHelpText>This field is used if a notification is grouped. Target Id of the record where to send the user after clicking page. You can either provide this or
        the target page reference value.</inlineHelpText>
    <label>Target Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

notification-engine/main/default/objects/NotificationGroup__c/fields/TargetReference__c.field-meta.xml
<CustomField>
    <fullName>TargetReference__c</fullName>
    <inlineHelpText>This field is used if a notification is grouped. Target page reference where to send the user after clicking page. You can either provide this or the target Id value.</inlineHelpText>
    <label>Target Page reference</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

notification-engine/main/default/objects/NotificationGroup__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <inlineHelpText>Write the title of the notification. This field does not support merge fields. Messages with values larger than 250 characters will be truncated.</inlineHelpText>
    <label>Title</label>
    <length>250</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

notification-engine/main/default/globalValueSets/NotificationType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>SFDefaultNotification</fullName>
        <label>SF Default Notification (notification-engine)</label>
    </customValue>
    <masterLabel>Notification Type</masterLabel>
</GlobalValueSet>

notification-engine/main/default/classes/SFNotificationConstants.cls
/**
 *
 * @description Constants
 *
 * @see SFNotification
 * @see SFNotificationBatch
 * @see SFNotificationGroupBatch
 *
 * @date 2021-02-07
 * @author Manjit Singh
 */
public with sharing class SFNotificationConstants {
    public static String SUCCESS = Label.SFNotificationSuccess;
    public static String ERROR = Label.SFNotificationError;
    public static String QUEUED = Label.SFNotificationQueued;

    public static String MESSAGE_BLANK_TITLE_OR_BODY = Label.SFNotificationErrorTitleBody;
    public static String MESSAGE_BLANK_TYPE = Label.SFNotificationErrorNotificationType ;
    public static String MESSAGE_BLANK_PRIORITY = Label.SFNotificationErrorPriority;
    public static String MESSAGE_BLANK_TARGET_ID = Label.SFNotificationErrorTarget;
    public static String MESSAGE_BLANK_RECIPIENTS = Label.SFNotificationErrorRecipient;

    // General
    public static String DEFAULT_NOTIFICATION_TYPE = 'SFDefaultNotification';
    public static String TEST_MESSAGE_ONE_NOTIF_QUEUED = 'A notification should have been created in queued status';
    public static String TEST_MESSAGE_ONE_GROUP_CREATED = 'A notification groups should have been created.';
    public static String TEST_MESSAGE_BATCH_SUCCESS = 'Batch should complete successfully as all fields are filled';
    public static String TEST_MESSAGE_BATCH_FAILURE = 'Batch should have failed. Mandatory fields are missing';

    public static String QUERY_GROUP_BATCH = 'SELECT OwnerId, Group__c FROM Notification__c WHERE ' +
            'Group__c != NULL AND Group__r.Status__c = \'' +
            QUEUED + '\' ORDER BY Priority__c ASC';

    public static String QUERY_BATCH = 'SELECT Body__c, Error__c, Group__c, Id, NotificationType__c, ' +
            'OwnerId, TargetReference__c, TargetId__c, Priority__c, Status__c, Title__c FROM ' +
            'Notification__c WHERE Group__c = NULL AND Status__c = \'' + QUEUED + '\' ' +
            'ORDER BY Priority__c ASC ';
}