notification-engine/main/default/objects/Notification__c/Notification__c.object-meta.xml
<CustomObject>
    <description>This object stores the individual notification. The notification can be linked to a group. If linked to a group, the notifications are batched together, and the Title and body are taken from the group.</description>
    <label>Notification</label>
    <nameField>
        <displayFormat>NOTIF-{YYYY}{MM}{DD}-{00000}</displayFormat>
        <label>#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

notification-engine/main/default/objects/Notification__c/fields/Body__c.field-meta.xml
<CustomField>
    <fullName>Body__c</fullName>
    <description>Write the body of the notification. This field support merge fields for user object. Example: {!User.Field__c} messages with values larger than 750 characters will be truncated.</description>
    <inlineHelpText>Write the body of the notification. This field support merge fields for user object. Example: {!User.Field__c} messages with values larger than 750 characters will be truncated.</inlineHelpText>
    <label>Body</label>
    <length>750</length>
    <type>LongTextArea</type>
</CustomField>

notification-engine/main/default/objects/Notification__c/fields/Error__c.field-meta.xml
<CustomField>
    <fullName>Error__c</fullName>
    <description>Stores error message for notification if any</description>
    <inlineHelpText>Error message</inlineHelpText>
    <label>Error</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

notification-engine/main/default/objects/Notification__c/fields/NotificationType__c.field-meta.xml
<CustomField>
    <fullName>NotificationType__c</fullName>
    <inlineHelpText>The custom notification Developer name created in Salesforce.</inlineHelpText>
    <label>Notification Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NotificationType</valueSetName>
    </valueSet>
</CustomField>

notification-engine/main/default/objects/Notification__c/fields/TargetId__c.field-meta.xml
<CustomField>
    <fullName>TargetId__c</fullName>
    <defaultValue>&apos;000000000000000AAA&apos;</defaultValue>
    <inlineHelpText>This field is ignored if a notification is grouped. Target Id of the record where to send the user after clicking page. You can either provide this or
        the target page reference value.</inlineHelpText>
    <label>Target Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

notification-engine/main/default/objects/Notification__c/fields/TargetReference__c.field-meta.xml
<CustomField>
    <fullName>TargetReference__c</fullName>
    <inlineHelpText>This field is ignored if a notification is grouped.Target page reference where to send the user
        after clicking page. You can either provide this or the target Id value.</inlineHelpText>
    <label>Target Page reference</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

notification-engine/main/default/objects/Notification__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <description>Write the title of the notification. This field support merge fields for user object. Example: {!User.Field__c} messages with values larger than 250 characters will be truncated.</description>
    <externalId>true</externalId>
    <inlineHelpText>Write the title of the notification. This field support merge fields for user object. Example: {!User.Field__c} messages with values larger than 250 characters will be truncated.</inlineHelpText>
    <label>Title</label>
    <length>250</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

notification-engine/main/default/globalValueSets/NotificationType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>SFDefaultNotification</fullName>
        <label>SF Default Notification (notification-engine)</label>
    </customValue>
    <masterLabel>Notification Type</masterLabel>
</GlobalValueSet>

notification-engine/main/default/classes/SFNotificationBatch.cls
/**
 *
 * @description This class is a batch for individual notifications.
 * It sends notifications individually and takes care of limits i.e
 * sends upto 10K notification events per hour.
 *
 * @see SFNotification
 *
 * @date 2021-02-07
 * @author Manjit Singh
 */
public with sharing class SFNotificationBatch implements Database.Batchable<SObject> {

    String query;
    SFNotificationHelper helper = new SFNotificationHelper();
    Map<String, Id> notificationTypes = helper.getNotificationTypes();
    List<Notification__c> notifications = new List<Notification__c>();


    public SFNotificationBatch(String query) {
        this.query = query;
    }

    public Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(this.query);
    }

    public void execute(Database.BatchableContext bc, List<Notification__c> scope) {

        for (Notification__c notification : scope) {
            try {
                helper.createNotifications(notificationTypes.get(notification.NotificationType__c),
                        notification.Title__c, notification.Body__c, notification.TargetId__c,
                        notification.TargetReference__c, new Set<String>{
                                notification.OwnerId
                        });
                notifications.add(new Notification__c(
                        Id = notification.Id, Status__c = SFNotificationConstants.SUCCESS, Error__c = null
                ));
            } catch (Exception e) {
                notifications.add(new Notification__c(
                        Id = notification.Id, Status__c = SFNotificationConstants.ERROR,
                        Error__c = e.getMessage() + ' ' + e.getStackTraceString()
                ));
            }
            update notifications;
        }
    }

    public void finish(Database.BatchableContext bc) {

    }
}