notification-engine/main/default/objects/Notification__c/Notification__c.object-meta.xml
<CustomObject>
    <description>This object stores the individual notification. The notification can be linked to a group. If linked to a group, the notifications are batched together, and the Title and body are taken from the group.</description>
    <label>Notification</label>
    <nameField>
        <displayFormat>NOTIF-{YYYY}{MM}{DD}-{00000}</displayFormat>
        <label>#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

notification-engine/main/default/objects/Notification__c/fields/Body__c.field-meta.xml
<CustomField>
    <fullName>Body__c</fullName>
    <description>Write the body of the notification. This field support merge fields for user object. Example: {!User.Field__c} messages with values larger than 750 characters will be truncated.</description>
    <inlineHelpText>Write the body of the notification. This field support merge fields for user object. Example: {!User.Field__c} messages with values larger than 750 characters will be truncated.</inlineHelpText>
    <label>Body</label>
    <length>750</length>
    <type>LongTextArea</type>
</CustomField>

notification-engine/main/default/objects/Notification__c/fields/Error__c.field-meta.xml
<CustomField>
    <fullName>Error__c</fullName>
    <description>Stores error message for notification if any</description>
    <inlineHelpText>Error message</inlineHelpText>
    <label>Error</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

notification-engine/main/default/objects/Notification__c/fields/Group__c.field-meta.xml
<CustomField>
    <fullName>Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The group with which this notification is attached to.</description>
    <label>Group</label>
    <referenceTo>NotificationGroup__c</referenceTo>
    <relationshipLabel>Notifications</relationshipLabel>
    <relationshipName>Notifications</relationshipName>
    <type>Lookup</type>
</CustomField>

notification-engine/main/default/objects/Notification__c/fields/NotificationType__c.field-meta.xml
<CustomField>
    <fullName>NotificationType__c</fullName>
    <inlineHelpText>The custom notification Developer name created in Salesforce.</inlineHelpText>
    <label>Notification Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NotificationType</valueSetName>
    </valueSet>
</CustomField>

notification-engine/main/default/objects/Notification__c/fields/TargetId__c.field-meta.xml
<CustomField>
    <fullName>TargetId__c</fullName>
    <defaultValue>&apos;000000000000000AAA&apos;</defaultValue>
    <inlineHelpText>This field is ignored if a notification is grouped. Target Id of the record where to send the user after clicking page. You can either provide this or
        the target page reference value.</inlineHelpText>
    <label>Target Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

notification-engine/main/default/objects/Notification__c/fields/TargetReference__c.field-meta.xml
<CustomField>
    <fullName>TargetReference__c</fullName>
    <inlineHelpText>This field is ignored if a notification is grouped.Target page reference where to send the user
        after clicking page. You can either provide this or the target Id value.</inlineHelpText>
    <label>Target Page reference</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

notification-engine/main/default/objects/Notification__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <description>Write the title of the notification. This field support merge fields for user object. Example: {!User.Field__c} messages with values larger than 250 characters will be truncated.</description>
    <externalId>true</externalId>
    <inlineHelpText>Write the title of the notification. This field support merge fields for user object. Example: {!User.Field__c} messages with values larger than 250 characters will be truncated.</inlineHelpText>
    <label>Title</label>
    <length>250</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

notification-engine/main/default/objects/NotificationGroup__c/NotificationGroup__c.object-meta.xml
<CustomObject>
    <description>A notification group which stores a single message to be sent to users. This can be a login message/welcome message etc or some other generic message.</description>
    <label>Notification Group</label>
    <nameField>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notification Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

notification-engine/main/default/objects/NotificationGroup__c/fields/Body__c.field-meta.xml
<CustomField>
    <fullName>Body__c</fullName>
    <inlineHelpText>Write the body of the notification. This field support merge fields for user object. Example: {!User.Field__c} messages with values larger than 750 characters will be truncated.</inlineHelpText>
    <label>Body</label>
    <length>750</length>
    <type>LongTextArea</type>
</CustomField>

notification-engine/main/default/objects/NotificationGroup__c/fields/NotificationType__c.field-meta.xml
<CustomField>
    <fullName>NotificationType__c</fullName>
    <label>Notification Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NotificationType</valueSetName>
    </valueSet>
</CustomField>

notification-engine/main/default/objects/NotificationGroup__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of this notification message.</description>
    <inlineHelpText>Status of this notification. Success means that notification was sent successfully, the delivery depends on reciever.</inlineHelpText>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Queued</fullName>
                <default>true</default>
                <label>Queued</label>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

notification-engine/main/default/objects/NotificationGroup__c/fields/TargetId__c.field-meta.xml
<CustomField>
    <fullName>TargetId__c</fullName>
    <defaultValue>&apos;000000000000000AAA&apos;</defaultValue>
    <inlineHelpText>This field is used if a notification is grouped. Target Id of the record where to send the user after clicking page. You can either provide this or
        the target page reference value.</inlineHelpText>
    <label>Target Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

notification-engine/main/default/objects/NotificationGroup__c/fields/TargetReference__c.field-meta.xml
<CustomField>
    <fullName>TargetReference__c</fullName>
    <inlineHelpText>This field is used if a notification is grouped. Target page reference where to send the user after clicking page. You can either provide this or the target Id value.</inlineHelpText>
    <label>Target Page reference</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

notification-engine/main/default/objects/NotificationGroup__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <inlineHelpText>Write the title of the notification. This field does not support merge fields. Messages with values larger than 250 characters will be truncated.</inlineHelpText>
    <label>Title</label>
    <length>250</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

notification-engine/main/default/globalValueSets/NotificationType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>SFDefaultNotification</fullName>
        <label>SF Default Notification (notification-engine)</label>
    </customValue>
    <masterLabel>Notification Type</masterLabel>
</GlobalValueSet>

notification-engine/main/default/classes/SFNotificationGroupBatch.cls
/**
 *
 * @description This class is a batch for group notifications.
 * It sends notifications to multiple users at same time
 * and takes care of limits i.e sends upto 10K notification events per hour.
 *
 * @see SFNotification
 *
 * @date 2021-02-07
 * @author Manjit Singh
 */
public with sharing class SFNotificationGroupBatch implements Database.Batchable<SObject> {

    String query;
    SFNotificationHelper helper = new SFNotificationHelper();
    Map<String, Id> notificationTypes = helper.getNotificationTypes();
    List<NotificationGroup__c> groups = new List<NotificationGroup__c>();

    public SFNotificationGroupBatch(String query) {
        this.query = query;
    }

    public Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(this.query);
    }

    public void execute(Database.BatchableContext bc, List<Notification__c> scope) {
        Map<Id, Set<String>> groupWithRecipient = new Map<Id, Set<String>>();
        Map<Id, Set<Id>> groupWithNotification = new Map<Id, Set<Id>>();
        List<Notification__c> notifications = new List<Notification__c>();

        for (Notification__c notification : scope) {
            if (!groupWithRecipient.containsKey(notification.Group__c)) {
                groupWithRecipient.put(notification.Group__c, new Set<String>());
            }
            groupWithRecipient.get(notification.Group__c).add(notification.OwnerId);
            if (!groupWithNotification.containsKey(notification.Group__c)) {
                groupWithNotification.put(notification.Group__c, new Set<Id>());
            }
            groupWithNotification.get(notification.Group__c).add(notification.Id);
        }

        Map<Id, NotificationGroup__c> notificationGroupMap = new Map<Id, NotificationGroup__c>([
                SELECT Title__c,Body__c,TargetId__c, TargetReference__c, NotificationType__c
                FROM NotificationGroup__c
        ]);

        for (Id groupId : groupWithRecipient.keySet()) {
            NotificationGroup__c notificationGroup = notificationGroupMap.get(groupId);
            try {
                helper.createNotifications(notificationTypes.get(notificationGroup.NotificationType__c),
                        notificationGroup.Title__c, notificationGroup.Body__c, notificationGroup.TargetId__c,
                        notificationGroup.TargetReference__c, groupWithRecipient.get(groupId));
                groups.add(new NotificationGroup__c(
                        Id = groupId, Status__c = SFNotificationConstants.SUCCESS, Error__c = null
                ));
                // Update all children of the group as well.
                notifications.addAll(this.updateChildNotifications(
                        groupWithNotification.get(groupId), SFNotificationConstants.SUCCESS
                ));
            } catch (Exception e) {
                groups.add(new NotificationGroup__c(
                        Id = groupId, Status__c = SFNotificationConstants.ERROR,
                        Error__c = e.getMessage() + ' ' + e.getStackTraceString()
                ));
                // Update all children of the group as well.
                notifications.addAll(this.updateChildNotifications(
                        groupWithNotification.get(groupId), SFNotificationConstants.ERROR
                ));
            }
        }
        update groups;
        update notifications;
    }

    private List<Notification__c> updateChildNotifications(Set<Id> notificationIds, String message) {
        List<Notification__c> notifications = new List<Notification__c>();
        for (Id notificationId : notificationIds) {
            notifications.add(new Notification__c(
                    Id = notificationId, Status__c = message
            ));
        }
        return notifications;
    }

    public void finish(Database.BatchableContext bc) {

    }
}