notification-engine/main/default/objects/NotificationGroup__c/NotificationGroup__c.object-meta.xml
<CustomObject>
    <description>A notification group which stores a single message to be sent to users. This can be a login message/welcome message etc or some other generic message.</description>
    <label>Notification Group</label>
    <nameField>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notification Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

notification-engine/main/default/objects/NotificationGroup__c/fields/Body__c.field-meta.xml
<CustomField>
    <fullName>Body__c</fullName>
    <inlineHelpText>Write the body of the notification. This field support merge fields for user object. Example: {!User.Field__c} messages with values larger than 750 characters will be truncated.</inlineHelpText>
    <label>Body</label>
    <length>750</length>
    <type>LongTextArea</type>
</CustomField>

notification-engine/main/default/objects/NotificationGroup__c/fields/NotificationType__c.field-meta.xml
<CustomField>
    <fullName>NotificationType__c</fullName>
    <label>Notification Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NotificationType</valueSetName>
    </valueSet>
</CustomField>

notification-engine/main/default/objects/NotificationGroup__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of this notification message.</description>
    <inlineHelpText>Status of this notification. Success means that notification was sent successfully, the delivery depends on reciever.</inlineHelpText>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Queued</fullName>
                <default>true</default>
                <label>Queued</label>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

notification-engine/main/default/objects/NotificationGroup__c/fields/TargetId__c.field-meta.xml
<CustomField>
    <fullName>TargetId__c</fullName>
    <defaultValue>&apos;000000000000000AAA&apos;</defaultValue>
    <inlineHelpText>This field is used if a notification is grouped. Target Id of the record where to send the user after clicking page. You can either provide this or
        the target page reference value.</inlineHelpText>
    <label>Target Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

notification-engine/main/default/objects/NotificationGroup__c/fields/TargetReference__c.field-meta.xml
<CustomField>
    <fullName>TargetReference__c</fullName>
    <inlineHelpText>This field is used if a notification is grouped. Target page reference where to send the user after clicking page. You can either provide this or the target Id value.</inlineHelpText>
    <label>Target Page reference</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

notification-engine/main/default/objects/NotificationGroup__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <inlineHelpText>Write the title of the notification. This field does not support merge fields. Messages with values larger than 250 characters will be truncated.</inlineHelpText>
    <label>Title</label>
    <length>250</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

notification-engine/main/default/globalValueSets/NotificationType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>SFDefaultNotification</fullName>
        <label>SF Default Notification (notification-engine)</label>
    </customValue>
    <masterLabel>Notification Type</masterLabel>
</GlobalValueSet>

notification-engine/main/default/classes/SFNotificationHelper.cls
/**
 *
 * @description This class is a helper and provides methods for
 * batch classes and SFNotification class
 *
 * @see SFNotification
 *
 * @date 2021-02-07
 * @author Manjit Singh
 */

public with sharing class SFNotificationHelper {

    public NotificationGroup__c createGroupIfNotExisting(String groupName, String notificationType, String title, String body, Id targetId, String pageRef) {
        List<NotificationGroup__c> groups = [
                SELECT Id, Name
                FROM NotificationGroup__c
                WHERE Name = :groupName
        ];

        if (groups.isEmpty()) {
            NotificationGroup__c notificationGroup = new NotificationGroup__c(
                    Name = groupName, Title__c = title, Body__c = body,
                    Status__c = SFNotificationConstants.QUEUED,
                    NotificationType__c = notificationType, TargetId__c = targetId,
                    TargetReference__c = pageRef
            );
            insert notificationGroup;
            return notificationGroup;
        }
        return groups.get(0);
    }

    public void createNotifications(Id notificationId, String title, String body, Id recordId, String pageRef, Set<String> recipientsIds) {
        Messaging.CustomNotification notification = new Messaging.CustomNotification();
        notification.setTitle(title);
        notification.setBody(body);
        notification.setNotificationTypeId(notificationId);
        notification.setTargetId(recordId);
        notification.setTargetPageRef(pageRef);
        notification.send(recipientsIds);
    }

    public Map<String, Id> getNotificationTypes() {
        Map<String, Id> notificationTypes = new Map<String, Id>();
        for (CustomNotificationType customNotificationType : [
                SELECT Id, DeveloperName,
                        CustomNotifTypeName
                FROM CustomNotificationType
        ]) {
            notificationTypes.put(customNotificationType.DeveloperName, customNotificationType.Id);
        }
        return notificationTypes;
    }
}