notification-engine/main/default/objects/NotificationGroup__c/NotificationGroup__c.object-meta.xml
<CustomObject>
    <description>A notification group which stores a single message to be sent to users. This can be a login message/welcome message etc or some other generic message.</description>
    <label>Notification Group</label>
    <nameField>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notification Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

notification-engine/main/default/objects/NotificationGroup__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of this notification message.</description>
    <inlineHelpText>Status of this notification. Success means that notification was sent successfully, the delivery depends on reciever.</inlineHelpText>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Queued</fullName>
                <default>true</default>
                <label>Queued</label>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

notification-engine/main/default/classes/SFNotificationGroupBatchTest.cls
/**
 *
 * @description Test class for SFNotificationBatch
 *
 * @see SFNotificationBatch
 *
 * @date 2021-02-07
 * @author Manjit Singh
 */
@IsTest(SeeAllData=false)
private with sharing class SFNotificationGroupBatchTest {
    @TestSetup private static void createData() {
        insert new Account(Name = 'SFNotificationSchedulerTest');
    }

    @IsTest private static void batchSuccessTest() {
        Account account = [SELECT Id FROM Account LIMIT 1];
        SFNotification notif = new SFNotification(SFNotificationConstants.DEFAULT_NOTIFICATION_TYPE,
                'Test Group', 'Title', 'Body');

        notif.setRecordId(account.Id).addRecipient(UserInfo.getUserId()).setPriority(1000).enqueue();

        NotificationGroup__c notificationGroup = [SELECT Status__c FROM NotificationGroup__c LIMIT 1];

        System.assertEquals(SFNotificationConstants.QUEUED, notificationGroup.Status__c,
                SFNotificationConstants.TEST_MESSAGE_ONE_GROUP_CREATED);
        Test.startTest();
        Database.executeBatch(new SFNotificationGroupBatch(SFNotificationConstants.QUERY_GROUP_BATCH), 200);
        Test.stopTest();
        notificationGroup = [SELECT Status__c FROM NotificationGroup__c LIMIT 1];

        System.assertEquals(SFNotificationConstants.SUCCESS, notificationGroup.Status__c,
                SFNotificationConstants.TEST_MESSAGE_BATCH_SUCCESS);

    }
}